version: '3.5'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5556:5432/tcp
    networks:
      - tn-booking-network

networks:
  tn-booking-network:
    driver: bridge
    name: tn-booking-network
