// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: note_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STATUS_NOTE int32

const (
	STATUS_NOTE_READ     STATUS_NOTE = 0
	STATUS_NOTE_NOT_READ STATUS_NOTE = 1
)

// Enum value maps for STATUS_NOTE.
var (
	STATUS_NOTE_name = map[int32]string{
		0: "READ",
		1: "NOT_READ",
	}
	STATUS_NOTE_value = map[string]int32{
		"READ":     0,
		"NOT_READ": 1,
	}
)

func (x STATUS_NOTE) Enum() *STATUS_NOTE {
	p := new(STATUS_NOTE)
	*p = x
	return p
}

func (x STATUS_NOTE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATUS_NOTE) Descriptor() protoreflect.EnumDescriptor {
	return file_note_service_proto_enumTypes[0].Descriptor()
}

func (STATUS_NOTE) Type() protoreflect.EnumType {
	return &file_note_service_proto_enumTypes[0]
}

func (x STATUS_NOTE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATUS_NOTE.Descriptor instead.
func (STATUS_NOTE) EnumDescriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{0}
}

type SetNoteSettingsRequest_TYPE_NOTE int32

const (
	SetNoteSettingsRequest_EMAIL SetNoteSettingsRequest_TYPE_NOTE = 0
	SetNoteSettingsRequest_LIFE  SetNoteSettingsRequest_TYPE_NOTE = 1
)

// Enum value maps for SetNoteSettingsRequest_TYPE_NOTE.
var (
	SetNoteSettingsRequest_TYPE_NOTE_name = map[int32]string{
		0: "EMAIL",
		1: "LIFE",
	}
	SetNoteSettingsRequest_TYPE_NOTE_value = map[string]int32{
		"EMAIL": 0,
		"LIFE":  1,
	}
)

func (x SetNoteSettingsRequest_TYPE_NOTE) Enum() *SetNoteSettingsRequest_TYPE_NOTE {
	p := new(SetNoteSettingsRequest_TYPE_NOTE)
	*p = x
	return p
}

func (x SetNoteSettingsRequest_TYPE_NOTE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetNoteSettingsRequest_TYPE_NOTE) Descriptor() protoreflect.EnumDescriptor {
	return file_note_service_proto_enumTypes[1].Descriptor()
}

func (SetNoteSettingsRequest_TYPE_NOTE) Type() protoreflect.EnumType {
	return &file_note_service_proto_enumTypes[1]
}

func (x SetNoteSettingsRequest_TYPE_NOTE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetNoteSettingsRequest_TYPE_NOTE.Descriptor instead.
func (SetNoteSettingsRequest_TYPE_NOTE) EnumDescriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{2, 0}
}

type NoteSorting_TYPE_SORTING int32

const (
	NoteSorting_BY_CREATED_AT NoteSorting_TYPE_SORTING = 0
	NoteSorting_BY_READ_AT    NoteSorting_TYPE_SORTING = 1
)

// Enum value maps for NoteSorting_TYPE_SORTING.
var (
	NoteSorting_TYPE_SORTING_name = map[int32]string{
		0: "BY_CREATED_AT",
		1: "BY_READ_AT",
	}
	NoteSorting_TYPE_SORTING_value = map[string]int32{
		"BY_CREATED_AT": 0,
		"BY_READ_AT":    1,
	}
)

func (x NoteSorting_TYPE_SORTING) Enum() *NoteSorting_TYPE_SORTING {
	p := new(NoteSorting_TYPE_SORTING)
	*p = x
	return p
}

func (x NoteSorting_TYPE_SORTING) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoteSorting_TYPE_SORTING) Descriptor() protoreflect.EnumDescriptor {
	return file_note_service_proto_enumTypes[2].Descriptor()
}

func (NoteSorting_TYPE_SORTING) Type() protoreflect.EnumType {
	return &file_note_service_proto_enumTypes[2]
}

func (x NoteSorting_TYPE_SORTING) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoteSorting_TYPE_SORTING.Descriptor instead.
func (NoteSorting_TYPE_SORTING) EnumDescriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{7, 0}
}

type GetNoteSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNoteSettingsRequest) Reset() {
	*x = GetNoteSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteSettingsRequest) ProtoMessage() {}

func (x *GetNoteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetNoteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{0}
}

type GetNoteSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsEmailOn bool `protobuf:"varint,1,opt,name=is_email_on,json=isEmailOn,proto3" json:"is_email_on,omitempty"`
	IsLifeOn  bool `protobuf:"varint,2,opt,name=is_life_on,json=isLifeOn,proto3" json:"is_life_on,omitempty"`
}

func (x *GetNoteSettingsResponse) Reset() {
	*x = GetNoteSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoteSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteSettingsResponse) ProtoMessage() {}

func (x *GetNoteSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetNoteSettingsResponse) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetNoteSettingsResponse) GetIsEmailOn() bool {
	if x != nil {
		return x.IsEmailOn
	}
	return false
}

func (x *GetNoteSettingsResponse) GetIsLifeOn() bool {
	if x != nil {
		return x.IsLifeOn
	}
	return false
}

type SetNoteSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SetNoteSettingsRequest_TYPE_NOTE `protobuf:"varint,1,opt,name=type,proto3,enum=booking.SetNoteSettingsRequest_TYPE_NOTE" json:"type,omitempty"`
	IsOn bool                             `protobuf:"varint,2,opt,name=is_on,json=isOn,proto3" json:"is_on,omitempty"`
}

func (x *SetNoteSettingsRequest) Reset() {
	*x = SetNoteSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNoteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNoteSettingsRequest) ProtoMessage() {}

func (x *SetNoteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNoteSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetNoteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetNoteSettingsRequest) GetType() SetNoteSettingsRequest_TYPE_NOTE {
	if x != nil {
		return x.Type
	}
	return SetNoteSettingsRequest_EMAIL
}

func (x *SetNoteSettingsRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

type SetNoteSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNoteSettingsResponse) Reset() {
	*x = SetNoteSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNoteSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNoteSettingsResponse) ProtoMessage() {}

func (x *SetNoteSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNoteSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetNoteSettingsResponse) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{3}
}

type GetNotesCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNotesCountRequest) Reset() {
	*x = GetNotesCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotesCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesCountRequest) ProtoMessage() {}

func (x *GetNotesCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesCountRequest.ProtoReflect.Descriptor instead.
func (*GetNotesCountRequest) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{4}
}

type GetNotesCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetNotesCountResponse) Reset() {
	*x = GetNotesCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotesCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesCountResponse) ProtoMessage() {}

func (x *GetNotesCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesCountResponse.ProtoReflect.Descriptor instead.
func (*GetNotesCountResponse) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetNotesCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetNotesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    STATUS_NOTE  `protobuf:"varint,1,opt,name=type,proto3,enum=booking.STATUS_NOTE" json:"type,omitempty"`
	Limit   uint32       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  uint32       `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Sorting *NoteSorting `protobuf:"bytes,4,opt,name=sorting,proto3" json:"sorting,omitempty"`
}

func (x *GetNotesRequest) Reset() {
	*x = GetNotesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesRequest) ProtoMessage() {}

func (x *GetNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesRequest.ProtoReflect.Descriptor instead.
func (*GetNotesRequest) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotesRequest) GetType() STATUS_NOTE {
	if x != nil {
		return x.Type
	}
	return STATUS_NOTE_READ
}

func (x *GetNotesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetNotesRequest) GetSorting() *NoteSorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

type NoteSorting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type NoteSorting_TYPE_SORTING `protobuf:"varint,1,opt,name=type,proto3,enum=booking.NoteSorting_TYPE_SORTING" json:"type,omitempty"`
	Asc  bool                     `protobuf:"varint,2,opt,name=asc,proto3" json:"asc,omitempty"`
}

func (x *NoteSorting) Reset() {
	*x = NoteSorting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteSorting) ProtoMessage() {}

func (x *NoteSorting) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteSorting.ProtoReflect.Descriptor instead.
func (*NoteSorting) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{7}
}

func (x *NoteSorting) GetType() NoteSorting_TYPE_SORTING {
	if x != nil {
		return x.Type
	}
	return NoteSorting_BY_CREATED_AT
}

func (x *NoteSorting) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type GetNotesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notes []*SystemNote `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
}

func (x *GetNotesResponse) Reset() {
	*x = GetNotesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesResponse) ProtoMessage() {}

func (x *GetNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesResponse.ProtoReflect.Descriptor instead.
func (*GetNotesResponse) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotesResponse) GetNotes() []*SystemNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

type ReadNotesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ReadNotesRequest) Reset() {
	*x = ReadNotesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotesRequest) ProtoMessage() {}

func (x *ReadNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotesRequest.ProtoReflect.Descriptor instead.
func (*ReadNotesRequest) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadNotesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReadNotesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadNotesResponse) Reset() {
	*x = ReadNotesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotesResponse) ProtoMessage() {}

func (x *ReadNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotesResponse.ProtoReflect.Descriptor instead.
func (*ReadNotesResponse) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{10}
}

type SystemNote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status      STATUS_NOTE `protobuf:"varint,2,opt,name=status,proto3,enum=booking.STATUS_NOTE" json:"status,omitempty"`
	AddressId   string      `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	AddressType AddressType `protobuf:"varint,4,opt,name=address_type,json=addressType,proto3,enum=booking.AddressType" json:"address_type,omitempty"`
	Header      string      `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Body        string      `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	ReadAt      string      `protobuf:"bytes,7,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	CreatedAt   string      `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SystemNote) Reset() {
	*x = SystemNote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNote) ProtoMessage() {}

func (x *SystemNote) ProtoReflect() protoreflect.Message {
	mi := &file_note_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNote.ProtoReflect.Descriptor instead.
func (*SystemNote) Descriptor() ([]byte, []int) {
	return file_note_service_proto_rawDescGZIP(), []int{11}
}

func (x *SystemNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemNote) GetStatus() STATUS_NOTE {
	if x != nil {
		return x.Status
	}
	return STATUS_NOTE_READ
}

func (x *SystemNote) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *SystemNote) GetAddressType() AddressType {
	if x != nil {
		return x.AddressType
	}
	return AddressType_UNKNOWN_OBJECT
}

func (x *SystemNote) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SystemNote) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SystemNote) GetReadAt() string {
	if x != nil {
		return x.ReadAt
	}
	return ""
}

func (x *SystemNote) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_note_service_proto protoreflect.FileDescriptor

var file_note_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x1a, 0x0d, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x57, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f,
	0x6e, 0x12, 0x1c, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x5f, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x69, 0x66, 0x65, 0x4f, 0x6e, 0x22,
	0x8e, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e,
	0x4f, 0x54, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6e, 0x22, 0x20,
	0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x4d, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x46, 0x45, 0x10, 0x01,
	0x22, 0x19, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x2e,
	0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x89,
	0x01, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x35,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x61, 0x73, 0x63, 0x22, 0x31, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x4f, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x59, 0x5f, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x41, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x59,
	0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x41, 0x54, 0x10, 0x01, 0x22, 0x3d, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29,
	0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f,
	0x74, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x10, 0x52, 0x65, 0x61,
	0x64, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22,
	0x13, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x86, 0x02, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e,
	0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x45, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64,
	0x12, 0x37, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x25, 0x0a,
	0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x45, 0x12, 0x08, 0x0a, 0x04,
	0x52, 0x45, 0x41, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x10, 0x01, 0x32, 0x91, 0x03, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x56, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x1f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4e,
	0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x41, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12,
	0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_note_service_proto_rawDescOnce sync.Once
	file_note_service_proto_rawDescData = file_note_service_proto_rawDesc
)

func file_note_service_proto_rawDescGZIP() []byte {
	file_note_service_proto_rawDescOnce.Do(func() {
		file_note_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_note_service_proto_rawDescData)
	})
	return file_note_service_proto_rawDescData
}

var file_note_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_note_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_note_service_proto_goTypes = []interface{}{
	(STATUS_NOTE)(0),                      // 0: booking.STATUS_NOTE
	(SetNoteSettingsRequest_TYPE_NOTE)(0), // 1: booking.SetNoteSettingsRequest.TYPE_NOTE
	(NoteSorting_TYPE_SORTING)(0),         // 2: booking.NoteSorting.TYPE_SORTING
	(*GetNoteSettingsRequest)(nil),        // 3: booking.GetNoteSettingsRequest
	(*GetNoteSettingsResponse)(nil),       // 4: booking.GetNoteSettingsResponse
	(*SetNoteSettingsRequest)(nil),        // 5: booking.SetNoteSettingsRequest
	(*SetNoteSettingsResponse)(nil),       // 6: booking.SetNoteSettingsResponse
	(*GetNotesCountRequest)(nil),          // 7: booking.GetNotesCountRequest
	(*GetNotesCountResponse)(nil),         // 8: booking.GetNotesCountResponse
	(*GetNotesRequest)(nil),               // 9: booking.GetNotesRequest
	(*NoteSorting)(nil),                   // 10: booking.NoteSorting
	(*GetNotesResponse)(nil),              // 11: booking.GetNotesResponse
	(*ReadNotesRequest)(nil),              // 12: booking.ReadNotesRequest
	(*ReadNotesResponse)(nil),             // 13: booking.ReadNotesResponse
	(*SystemNote)(nil),                    // 14: booking.SystemNote
	(AddressType)(0),                      // 15: booking.AddressType
}
var file_note_service_proto_depIdxs = []int32{
	1,  // 0: booking.SetNoteSettingsRequest.type:type_name -> booking.SetNoteSettingsRequest.TYPE_NOTE
	0,  // 1: booking.GetNotesRequest.type:type_name -> booking.STATUS_NOTE
	10, // 2: booking.GetNotesRequest.sorting:type_name -> booking.NoteSorting
	2,  // 3: booking.NoteSorting.type:type_name -> booking.NoteSorting.TYPE_SORTING
	14, // 4: booking.GetNotesResponse.notes:type_name -> booking.SystemNote
	0,  // 5: booking.SystemNote.status:type_name -> booking.STATUS_NOTE
	15, // 6: booking.SystemNote.address_type:type_name -> booking.AddressType
	3,  // 7: booking.Note.GetNoteSettings:input_type -> booking.GetNoteSettingsRequest
	5,  // 8: booking.Note.SetNoteSettings:input_type -> booking.SetNoteSettingsRequest
	7,  // 9: booking.Note.GetNotesCount:input_type -> booking.GetNotesCountRequest
	9,  // 10: booking.Note.GetNotes:input_type -> booking.GetNotesRequest
	12, // 11: booking.Note.ReadNotes:input_type -> booking.ReadNotesRequest
	4,  // 12: booking.Note.GetNoteSettings:output_type -> booking.GetNoteSettingsResponse
	6,  // 13: booking.Note.SetNoteSettings:output_type -> booking.SetNoteSettingsResponse
	8,  // 14: booking.Note.GetNotesCount:output_type -> booking.GetNotesCountResponse
	11, // 15: booking.Note.GetNotes:output_type -> booking.GetNotesResponse
	13, // 16: booking.Note.ReadNotes:output_type -> booking.ReadNotesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_note_service_proto_init() }
func file_note_service_proto_init() {
	if File_note_service_proto != nil {
		return
	}
	file_address_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_note_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNoteSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNoteSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNoteSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNoteSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotesCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotesCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoteSorting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemNote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_note_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_service_proto_goTypes,
		DependencyIndexes: file_note_service_proto_depIdxs,
		EnumInfos:         file_note_service_proto_enumTypes,
		MessageInfos:      file_note_service_proto_msgTypes,
	}.Build()
	File_note_service_proto = out.File
	file_note_service_proto_rawDesc = nil
	file_note_service_proto_goTypes = nil
	file_note_service_proto_depIdxs = nil
}
