// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.2
// source: report_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	SendBookingReport(ctx context.Context, in *SendBookingReportRequest, opts ...grpc.CallOption) (*SendBookingReportResponse, error)
	SendRoomReport(ctx context.Context, in *SendRoomReportRequest, opts ...grpc.CallOption) (*ReportRoomResponse, error)
	GetRoomReport(ctx context.Context, in *GetRoomReportRequest, opts ...grpc.CallOption) (*ReportRoomResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) SendBookingReport(ctx context.Context, in *SendBookingReportRequest, opts ...grpc.CallOption) (*SendBookingReportResponse, error) {
	out := new(SendBookingReportResponse)
	err := c.cc.Invoke(ctx, "/booking.ReportService/SendBookingReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) SendRoomReport(ctx context.Context, in *SendRoomReportRequest, opts ...grpc.CallOption) (*ReportRoomResponse, error) {
	out := new(ReportRoomResponse)
	err := c.cc.Invoke(ctx, "/booking.ReportService/SendRoomReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetRoomReport(ctx context.Context, in *GetRoomReportRequest, opts ...grpc.CallOption) (*ReportRoomResponse, error) {
	out := new(ReportRoomResponse)
	err := c.cc.Invoke(ctx, "/booking.ReportService/GetRoomReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	SendBookingReport(context.Context, *SendBookingReportRequest) (*SendBookingReportResponse, error)
	SendRoomReport(context.Context, *SendRoomReportRequest) (*ReportRoomResponse, error)
	GetRoomReport(context.Context, *GetRoomReportRequest) (*ReportRoomResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) SendBookingReport(context.Context, *SendBookingReportRequest) (*SendBookingReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBookingReport not implemented")
}
func (UnimplementedReportServiceServer) SendRoomReport(context.Context, *SendRoomReportRequest) (*ReportRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRoomReport not implemented")
}
func (UnimplementedReportServiceServer) GetRoomReport(context.Context, *GetRoomReportRequest) (*ReportRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomReport not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_SendBookingReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBookingReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).SendBookingReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.ReportService/SendBookingReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).SendBookingReport(ctx, req.(*SendBookingReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_SendRoomReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRoomReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).SendRoomReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.ReportService/SendRoomReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).SendRoomReport(ctx, req.(*SendRoomReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetRoomReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetRoomReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.ReportService/GetRoomReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetRoomReport(ctx, req.(*GetRoomReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBookingReport",
			Handler:    _ReportService_SendBookingReport_Handler,
		},
		{
			MethodName: "SendRoomReport",
			Handler:    _ReportService_SendRoomReport_Handler,
		},
		{
			MethodName: "GetRoomReport",
			Handler:    _ReportService_GetRoomReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report_service.proto",
}
