// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: room_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomSorting_TYPE_SORTING int32

const (
	RoomSorting_BY_PUBLISH_DATE       RoomSorting_TYPE_SORTING = 0
	RoomSorting_BY_CREATION_DATE_DATE RoomSorting_TYPE_SORTING = 1
)

// Enum value maps for RoomSorting_TYPE_SORTING.
var (
	RoomSorting_TYPE_SORTING_name = map[int32]string{
		0: "BY_PUBLISH_DATE",
		1: "BY_CREATION_DATE_DATE",
	}
	RoomSorting_TYPE_SORTING_value = map[string]int32{
		"BY_PUBLISH_DATE":       0,
		"BY_CREATION_DATE_DATE": 1,
	}
)

func (x RoomSorting_TYPE_SORTING) Enum() *RoomSorting_TYPE_SORTING {
	p := new(RoomSorting_TYPE_SORTING)
	*p = x
	return p
}

func (x RoomSorting_TYPE_SORTING) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomSorting_TYPE_SORTING) Descriptor() protoreflect.EnumDescriptor {
	return file_room_service_proto_enumTypes[0].Descriptor()
}

func (RoomSorting_TYPE_SORTING) Type() protoreflect.EnumType {
	return &file_room_service_proto_enumTypes[0]
}

func (x RoomSorting_TYPE_SORTING) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomSorting_TYPE_SORTING.Descriptor instead.
func (RoomSorting_TYPE_SORTING) EnumDescriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{28, 0}
}

type CreateInitialRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title              string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description        string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CreationDate       string   `protobuf:"bytes,3,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	PortalCodeOwner    uint32   `protobuf:"varint,4,opt,name=portalCodeOwner,proto3" json:"portalCodeOwner,omitempty"`
	PortalCodeAssignee uint32   `protobuf:"varint,5,opt,name=portalCodeAssignee,proto3" json:"portalCodeAssignee,omitempty"`
	TargetAudience     string   `protobuf:"bytes,6,opt,name=targetAudience,proto3" json:"targetAudience,omitempty"`
	Equipments         []string `protobuf:"bytes,7,rep,name=equipments,proto3" json:"equipments,omitempty"`
	Slots              []string `protobuf:"bytes,8,rep,name=slots,proto3" json:"slots,omitempty"`
	BookingIDs         []string `protobuf:"bytes,9,rep,name=bookingIDs,proto3" json:"bookingIDs,omitempty"`
}

func (x *CreateInitialRoomRequest) Reset() {
	*x = CreateInitialRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInitialRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInitialRoomRequest) ProtoMessage() {}

func (x *CreateInitialRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInitialRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateInitialRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInitialRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateInitialRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateInitialRoomRequest) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *CreateInitialRoomRequest) GetPortalCodeOwner() uint32 {
	if x != nil {
		return x.PortalCodeOwner
	}
	return 0
}

func (x *CreateInitialRoomRequest) GetPortalCodeAssignee() uint32 {
	if x != nil {
		return x.PortalCodeAssignee
	}
	return 0
}

func (x *CreateInitialRoomRequest) GetTargetAudience() string {
	if x != nil {
		return x.TargetAudience
	}
	return ""
}

func (x *CreateInitialRoomRequest) GetEquipments() []string {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *CreateInitialRoomRequest) GetSlots() []string {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *CreateInitialRoomRequest) GetBookingIDs() []string {
	if x != nil {
		return x.BookingIDs
	}
	return nil
}

type CreateInitialRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *CreateInitialRoomResponse) Reset() {
	*x = CreateInitialRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInitialRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInitialRoomResponse) ProtoMessage() {}

func (x *CreateInitialRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInitialRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateInitialRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInitialRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type UpdateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid               string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title              string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description        string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreationDate       string   `protobuf:"bytes,4,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	PortalCodeOwner    uint32   `protobuf:"varint,5,opt,name=portalCodeOwner,proto3" json:"portalCodeOwner,omitempty"`
	PortalCodeAssignee uint32   `protobuf:"varint,6,opt,name=portalCodeAssignee,proto3" json:"portalCodeAssignee,omitempty"`
	TargetAudience     string   `protobuf:"bytes,7,opt,name=targetAudience,proto3" json:"targetAudience,omitempty"`
	Equipments         []string `protobuf:"bytes,8,rep,name=equipments,proto3" json:"equipments,omitempty"`
	Slots              []string `protobuf:"bytes,9,rep,name=slots,proto3" json:"slots,omitempty"`
	BookingIDs         []string `protobuf:"bytes,10,rep,name=bookingIDs,proto3" json:"bookingIDs,omitempty"`
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoomRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoomRequest) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *UpdateRoomRequest) GetPortalCodeOwner() uint32 {
	if x != nil {
		return x.PortalCodeOwner
	}
	return 0
}

func (x *UpdateRoomRequest) GetPortalCodeAssignee() uint32 {
	if x != nil {
		return x.PortalCodeAssignee
	}
	return 0
}

func (x *UpdateRoomRequest) GetTargetAudience() string {
	if x != nil {
		return x.TargetAudience
	}
	return ""
}

func (x *UpdateRoomRequest) GetEquipments() []string {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *UpdateRoomRequest) GetSlots() []string {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *UpdateRoomRequest) GetBookingIDs() []string {
	if x != nil {
		return x.BookingIDs
	}
	return nil
}

type UpdateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type AddRoomSlotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots []*Slot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *AddRoomSlotsRequest) Reset() {
	*x = AddRoomSlotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomSlotsRequest) ProtoMessage() {}

func (x *AddRoomSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomSlotsRequest.ProtoReflect.Descriptor instead.
func (*AddRoomSlotsRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddRoomSlotsRequest) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type AddRoomSlotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
}

func (x *AddRoomSlotsResponse) Reset() {
	*x = AddRoomSlotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomSlotsResponse) ProtoMessage() {}

func (x *AddRoomSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomSlotsResponse.ProtoReflect.Descriptor instead.
func (*AddRoomSlotsResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddRoomSlotsResponse) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type UpdateRoomSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot *RoomSlot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *UpdateRoomSlotRequest) Reset() {
	*x = UpdateRoomSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomSlotRequest) ProtoMessage() {}

func (x *UpdateRoomSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomSlotRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomSlotRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoomSlotRequest) GetSlot() *RoomSlot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type UpdateRoomSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot *RoomSlot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *UpdateRoomSlotResponse) Reset() {
	*x = UpdateRoomSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomSlotResponse) ProtoMessage() {}

func (x *UpdateRoomSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomSlotResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomSlotResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoomSlotResponse) GetSlot() *RoomSlot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type AddRoomEquipmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipments []*Equipment `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"`
}

func (x *AddRoomEquipmentsRequest) Reset() {
	*x = AddRoomEquipmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomEquipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomEquipmentsRequest) ProtoMessage() {}

func (x *AddRoomEquipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomEquipmentsRequest.ProtoReflect.Descriptor instead.
func (*AddRoomEquipmentsRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddRoomEquipmentsRequest) GetEquipments() []*Equipment {
	if x != nil {
		return x.Equipments
	}
	return nil
}

type AddRoomEquipmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
}

func (x *AddRoomEquipmentsResponse) Reset() {
	*x = AddRoomEquipmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomEquipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomEquipmentsResponse) ProtoMessage() {}

func (x *AddRoomEquipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomEquipmentsResponse.ProtoReflect.Descriptor instead.
func (*AddRoomEquipmentsResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{9}
}

func (x *AddRoomEquipmentsResponse) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type UpdateRoomEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipment *RoomEquipment `protobuf:"bytes,1,opt,name=equipment,proto3" json:"equipment,omitempty"`
}

func (x *UpdateRoomEquipmentRequest) Reset() {
	*x = UpdateRoomEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomEquipmentRequest) ProtoMessage() {}

func (x *UpdateRoomEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomEquipmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRoomEquipmentRequest) GetEquipment() *RoomEquipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type UpdateRoomEquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipment *RoomEquipment `protobuf:"bytes,1,opt,name=equipment,proto3" json:"equipment,omitempty"`
}

func (x *UpdateRoomEquipmentResponse) Reset() {
	*x = UpdateRoomEquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomEquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomEquipmentResponse) ProtoMessage() {}

func (x *UpdateRoomEquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomEquipmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomEquipmentResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRoomEquipmentResponse) GetEquipment() *RoomEquipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type GetRoomsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit   uint32       `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  uint32       `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Query   string       `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Filter  *RoomFilter  `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Sorting *RoomSorting `protobuf:"bytes,5,opt,name=sorting,proto3" json:"sorting,omitempty"`
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRoomsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRoomsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetRoomsRequest) GetFilter() *RoomFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetRoomsRequest) GetSorting() *RoomSorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Count uint32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomsResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type ChangeRoomStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status AddressStatus `protobuf:"varint,2,opt,name=status,proto3,enum=booking.AddressStatus" json:"status,omitempty"`
}

func (x *ChangeRoomStatusRequest) Reset() {
	*x = ChangeRoomStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeRoomStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoomStatusRequest) ProtoMessage() {}

func (x *ChangeRoomStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoomStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeRoomStatusRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeRoomStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeRoomStatusRequest) GetStatus() AddressStatus {
	if x != nil {
		return x.Status
	}
	return AddressStatus_ADDRESS_STATUS
}

type RemoveRoomSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RemoveRoomSlotRequest) Reset() {
	*x = RemoveRoomSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoomSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomSlotRequest) ProtoMessage() {}

func (x *RemoveRoomSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomSlotRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomSlotRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRoomSlotRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RemoveRoomEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RemoveRoomEquipmentRequest) Reset() {
	*x = RemoveRoomEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoomEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomEquipmentRequest) ProtoMessage() {}

func (x *RemoveRoomEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomEquipmentRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveRoomEquipmentRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type AddReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Releases []*Release `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
}

func (x *AddReleaseRequest) Reset() {
	*x = AddReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReleaseRequest) ProtoMessage() {}

func (x *AddReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReleaseRequest.ProtoReflect.Descriptor instead.
func (*AddReleaseRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{19}
}

func (x *AddReleaseRequest) GetReleases() []*Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

type AddReleaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
}

func (x *AddReleaseResponse) Reset() {
	*x = AddReleaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReleaseResponse) ProtoMessage() {}

func (x *AddReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReleaseResponse.ProtoReflect.Descriptor instead.
func (*AddReleaseResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{20}
}

func (x *AddReleaseResponse) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type PrepareReportDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeline *Timeline `protobuf:"bytes,1,opt,name=timeline,proto3" json:"timeline,omitempty"`
	RoomID   string    `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *PrepareReportDataRequest) Reset() {
	*x = PrepareReportDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareReportDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReportDataRequest) ProtoMessage() {}

func (x *PrepareReportDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReportDataRequest.ProtoReflect.Descriptor instead.
func (*PrepareReportDataRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{21}
}

func (x *PrepareReportDataRequest) GetTimeline() *Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *PrepareReportDataRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type PrepareReportDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Releases   []*Release       `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	Slots      []*RoomSlot      `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	Equipments []*RoomEquipment `protobuf:"bytes,3,rep,name=equipments,proto3" json:"equipments,omitempty"`
}

func (x *PrepareReportDataResponse) Reset() {
	*x = PrepareReportDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareReportDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReportDataResponse) ProtoMessage() {}

func (x *PrepareReportDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReportDataResponse.ProtoReflect.Descriptor instead.
func (*PrepareReportDataResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{22}
}

func (x *PrepareReportDataResponse) GetReleases() []*Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *PrepareReportDataResponse) GetSlots() []*RoomSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *PrepareReportDataResponse) GetEquipments() []*RoomEquipment {
	if x != nil {
		return x.Equipments
	}
	return nil
}

type RoomFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedByMe         bool            `protobuf:"varint,1,opt,name=CreatedByMe,proto3" json:"CreatedByMe,omitempty"` // current_user=supervisor
	AwaitsMe            bool            `protobuf:"varint,2,opt,name=AwaitsMe,proto3" json:"AwaitsMe,omitempty"`
	CreatedAt           *Timeline       `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreationDate        *Timeline       `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Status              []AddressStatus `protobuf:"varint,5,rep,packed,name=status,proto3,enum=booking.AddressStatus" json:"status,omitempty"`
	PortalCodeOwners    []uint32        `protobuf:"varint,6,rep,packed,name=portal_code_owners,json=portalCodeOwners,proto3" json:"portal_code_owners,omitempty"`
	PortalCodeEmployees []uint32        `protobuf:"varint,7,rep,packed,name=portal_code_employees,json=portalCodeEmployees,proto3" json:"portal_code_employees,omitempty"`
}

func (x *RoomFilter) Reset() {
	*x = RoomFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomFilter) ProtoMessage() {}

func (x *RoomFilter) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomFilter.ProtoReflect.Descriptor instead.
func (*RoomFilter) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{23}
}

func (x *RoomFilter) GetCreatedByMe() bool {
	if x != nil {
		return x.CreatedByMe
	}
	return false
}

func (x *RoomFilter) GetAwaitsMe() bool {
	if x != nil {
		return x.AwaitsMe
	}
	return false
}

func (x *RoomFilter) GetCreatedAt() *Timeline {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomFilter) GetCreationDate() *Timeline {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *RoomFilter) GetStatus() []AddressStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RoomFilter) GetPortalCodeOwners() []uint32 {
	if x != nil {
		return x.PortalCodeOwners
	}
	return nil
}

func (x *RoomFilter) GetPortalCodeEmployees() []uint32 {
	if x != nil {
		return x.PortalCodeEmployees
	}
	return nil
}

type UpdateReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Release *Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
}

func (x *UpdateReleaseRequest) Reset() {
	*x = UpdateReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReleaseRequest) ProtoMessage() {}

func (x *UpdateReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReleaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateReleaseRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateReleaseRequest) GetRelease() *Release {
	if x != nil {
		return x.Release
	}
	return nil
}

type UpdateReleaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Release *Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
}

func (x *UpdateReleaseResponse) Reset() {
	*x = UpdateReleaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReleaseResponse) ProtoMessage() {}

func (x *UpdateReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReleaseResponse.ProtoReflect.Descriptor instead.
func (*UpdateReleaseResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateReleaseResponse) GetRelease() *Release {
	if x != nil {
		return x.Release
	}
	return nil
}

type RemoveReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RemoveReleaseRequest) Reset() {
	*x = RemoveReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReleaseRequest) ProtoMessage() {}

func (x *RemoveReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReleaseRequest.ProtoReflect.Descriptor instead.
func (*RemoveReleaseRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveReleaseRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RemoveReleaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RemoveReleaseResponse) Reset() {
	*x = RemoveReleaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReleaseResponse) ProtoMessage() {}

func (x *RemoveReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReleaseResponse.ProtoReflect.Descriptor instead.
func (*RemoveReleaseResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveReleaseResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RoomSorting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RoomSorting_TYPE_SORTING `protobuf:"varint,1,opt,name=type,proto3,enum=booking.RoomSorting_TYPE_SORTING" json:"type,omitempty"`
	Asc  bool                     `protobuf:"varint,2,opt,name=asc,proto3" json:"asc,omitempty"`
}

func (x *RoomSorting) Reset() {
	*x = RoomSorting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSorting) ProtoMessage() {}

func (x *RoomSorting) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSorting.ProtoReflect.Descriptor instead.
func (*RoomSorting) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{28}
}

func (x *RoomSorting) GetType() RoomSorting_TYPE_SORTING {
	if x != nil {
		return x.Type
	}
	return RoomSorting_BY_PUBLISH_DATE
}

func (x *RoomSorting) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type SetRoomArchivedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *SetRoomArchivedRequest) Reset() {
	*x = SetRoomArchivedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRoomArchivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomArchivedRequest) ProtoMessage() {}

func (x *SetRoomArchivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomArchivedRequest.ProtoReflect.Descriptor instead.
func (*SetRoomArchivedRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{29}
}

func (x *SetRoomArchivedRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type SetRoomPublishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *SetRoomPublishedRequest) Reset() {
	*x = SetRoomPublishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_service_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRoomPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomPublishedRequest) ProtoMessage() {}

func (x *SetRoomPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomPublishedRequest.ProtoReflect.Descriptor instead.
func (*SetRoomPublishedRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{30}
}

func (x *SetRoomPublishedRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

var File_room_service_proto protoreflect.FileDescriptor

var file_room_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x1a, 0x0a, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x02, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x49, 0x44, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x49, 0x44, 0x73, 0x22, 0x3e, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0xdb, 0x02, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64,
	0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x12, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49,
	0x44, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x49, 0x44, 0x73, 0x22, 0x37, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x3a, 0x0a,
	0x13, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x6c,
	0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x2c, 0x0a, 0x14, 0x41, 0x64, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x75, 0x75, 0x69, 0x64, 0x73, 0x22, 0x3e, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x3f, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c,
	0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x4e, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x52,
	0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x52,
	0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x75, 0x69, 0x64, 0x73, 0x22, 0x52, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x53, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0xb2, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x6f, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f,
	0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x22, 0x59, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x15, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x11, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x22, 0x2a, 0x0a,
	0x12, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x75, 0x75, 0x69, 0x64, 0x73, 0x22, 0x61, 0x0a, 0x18, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0xaa, 0x01, 0x0a,
	0x19, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x12, 0x36, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xc6, 0x02, 0x0a, 0x0a, 0x52, 0x6f,
	0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x4d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x4d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x77,
	0x61, 0x69, 0x74, 0x73, 0x4d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x41, 0x77,
	0x61, 0x69, 0x74, 0x73, 0x4d, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x12, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x32,
	0x0a, 0x15, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x13, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x73, 0x22, 0x42, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x07, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6f, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4f,
	0x52, 0x54, 0x49, 0x4e, 0x47, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x73, 0x63, 0x22, 0x3e, 0x0a,
	0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x12, 0x13, 0x0a,
	0x0f, 0x42, 0x59, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x5f, 0x44, 0x41, 0x54, 0x45,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x59, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x22, 0x30, 0x0a,
	0x16, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22,
	0x31, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x32, 0xbd, 0x0b, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x41, 0x64, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52,
	0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f,
	0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x1e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x23, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x12, 0x1e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x13, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x23, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x18, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x18, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x47, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x4e, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x20, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_service_proto_rawDescOnce sync.Once
	file_room_service_proto_rawDescData = file_room_service_proto_rawDesc
)

func file_room_service_proto_rawDescGZIP() []byte {
	file_room_service_proto_rawDescOnce.Do(func() {
		file_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_service_proto_rawDescData)
	})
	return file_room_service_proto_rawDescData
}

var file_room_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_room_service_proto_goTypes = []interface{}{
	(RoomSorting_TYPE_SORTING)(0),       // 0: booking.RoomSorting.TYPE_SORTING
	(*CreateInitialRoomRequest)(nil),    // 1: booking.CreateInitialRoomRequest
	(*CreateInitialRoomResponse)(nil),   // 2: booking.CreateInitialRoomResponse
	(*UpdateRoomRequest)(nil),           // 3: booking.UpdateRoomRequest
	(*UpdateRoomResponse)(nil),          // 4: booking.UpdateRoomResponse
	(*AddRoomSlotsRequest)(nil),         // 5: booking.AddRoomSlotsRequest
	(*AddRoomSlotsResponse)(nil),        // 6: booking.AddRoomSlotsResponse
	(*UpdateRoomSlotRequest)(nil),       // 7: booking.UpdateRoomSlotRequest
	(*UpdateRoomSlotResponse)(nil),      // 8: booking.UpdateRoomSlotResponse
	(*AddRoomEquipmentsRequest)(nil),    // 9: booking.AddRoomEquipmentsRequest
	(*AddRoomEquipmentsResponse)(nil),   // 10: booking.AddRoomEquipmentsResponse
	(*UpdateRoomEquipmentRequest)(nil),  // 11: booking.UpdateRoomEquipmentRequest
	(*UpdateRoomEquipmentResponse)(nil), // 12: booking.UpdateRoomEquipmentResponse
	(*GetRoomsRequest)(nil),             // 13: booking.GetRoomsRequest
	(*GetRoomsResponse)(nil),            // 14: booking.GetRoomsResponse
	(*GetRoomRequest)(nil),              // 15: booking.GetRoomRequest
	(*GetRoomResponse)(nil),             // 16: booking.GetRoomResponse
	(*ChangeRoomStatusRequest)(nil),     // 17: booking.ChangeRoomStatusRequest
	(*RemoveRoomSlotRequest)(nil),       // 18: booking.RemoveRoomSlotRequest
	(*RemoveRoomEquipmentRequest)(nil),  // 19: booking.RemoveRoomEquipmentRequest
	(*AddReleaseRequest)(nil),           // 20: booking.AddReleaseRequest
	(*AddReleaseResponse)(nil),          // 21: booking.AddReleaseResponse
	(*PrepareReportDataRequest)(nil),    // 22: booking.PrepareReportDataRequest
	(*PrepareReportDataResponse)(nil),   // 23: booking.PrepareReportDataResponse
	(*RoomFilter)(nil),                  // 24: booking.RoomFilter
	(*UpdateReleaseRequest)(nil),        // 25: booking.UpdateReleaseRequest
	(*UpdateReleaseResponse)(nil),       // 26: booking.UpdateReleaseResponse
	(*RemoveReleaseRequest)(nil),        // 27: booking.RemoveReleaseRequest
	(*RemoveReleaseResponse)(nil),       // 28: booking.RemoveReleaseResponse
	(*RoomSorting)(nil),                 // 29: booking.RoomSorting
	(*SetRoomArchivedRequest)(nil),      // 30: booking.SetRoomArchivedRequest
	(*SetRoomPublishedRequest)(nil),     // 31: booking.SetRoomPublishedRequest
	(*Room)(nil),                        // 32: booking.Room
	(*Slot)(nil),                        // 33: booking.Slot
	(*RoomSlot)(nil),                    // 34: booking.RoomSlot
	(*Equipment)(nil),                   // 35: booking.Equipment
	(*RoomEquipment)(nil),               // 36: booking.RoomEquipment
	(AddressStatus)(0),                  // 37: booking.AddressStatus
	(*Release)(nil),                     // 38: booking.Release
	(*Timeline)(nil),                    // 39: booking.Timeline
	(*emptypb.Empty)(nil),               // 40: google.protobuf.Empty
}
var file_room_service_proto_depIdxs = []int32{
	32, // 0: booking.CreateInitialRoomResponse.room:type_name -> booking.Room
	32, // 1: booking.UpdateRoomResponse.room:type_name -> booking.Room
	33, // 2: booking.AddRoomSlotsRequest.slots:type_name -> booking.Slot
	34, // 3: booking.UpdateRoomSlotRequest.slot:type_name -> booking.RoomSlot
	34, // 4: booking.UpdateRoomSlotResponse.slot:type_name -> booking.RoomSlot
	35, // 5: booking.AddRoomEquipmentsRequest.equipments:type_name -> booking.Equipment
	36, // 6: booking.UpdateRoomEquipmentRequest.equipment:type_name -> booking.RoomEquipment
	36, // 7: booking.UpdateRoomEquipmentResponse.equipment:type_name -> booking.RoomEquipment
	24, // 8: booking.GetRoomsRequest.filter:type_name -> booking.RoomFilter
	29, // 9: booking.GetRoomsRequest.sorting:type_name -> booking.RoomSorting
	32, // 10: booking.GetRoomsResponse.rooms:type_name -> booking.Room
	32, // 11: booking.GetRoomResponse.room:type_name -> booking.Room
	37, // 12: booking.ChangeRoomStatusRequest.status:type_name -> booking.AddressStatus
	38, // 13: booking.AddReleaseRequest.releases:type_name -> booking.Release
	39, // 14: booking.PrepareReportDataRequest.timeline:type_name -> booking.Timeline
	38, // 15: booking.PrepareReportDataResponse.releases:type_name -> booking.Release
	34, // 16: booking.PrepareReportDataResponse.slots:type_name -> booking.RoomSlot
	36, // 17: booking.PrepareReportDataResponse.equipments:type_name -> booking.RoomEquipment
	39, // 18: booking.RoomFilter.created_at:type_name -> booking.Timeline
	39, // 19: booking.RoomFilter.creation_date:type_name -> booking.Timeline
	37, // 20: booking.RoomFilter.status:type_name -> booking.AddressStatus
	38, // 21: booking.UpdateReleaseRequest.release:type_name -> booking.Release
	38, // 22: booking.UpdateReleaseResponse.release:type_name -> booking.Release
	0,  // 23: booking.RoomSorting.type:type_name -> booking.RoomSorting.TYPE_SORTING
	1,  // 24: booking.RoomService.CreateInitialRoom:input_type -> booking.CreateInitialRoomRequest
	3,  // 25: booking.RoomService.UpdateRoom:input_type -> booking.UpdateRoomRequest
	5,  // 26: booking.RoomService.AddRoomSlots:input_type -> booking.AddRoomSlotsRequest
	9,  // 27: booking.RoomService.AddRoomEquipments:input_type -> booking.AddRoomEquipmentsRequest
	7,  // 28: booking.RoomService.UpdateRoomSlot:input_type -> booking.UpdateRoomSlotRequest
	11, // 29: booking.RoomService.UpdateRoomEquipment:input_type -> booking.UpdateRoomEquipmentRequest
	18, // 30: booking.RoomService.RemoveRoomSlot:input_type -> booking.RemoveRoomSlotRequest
	19, // 31: booking.RoomService.RemoveRoomEquipment:input_type -> booking.RemoveRoomEquipmentRequest
	13, // 32: booking.RoomService.GetRooms:input_type -> booking.GetRoomsRequest
	13, // 33: booking.RoomService.GetArchivedRooms:input_type -> booking.GetRoomsRequest
	15, // 34: booking.RoomService.GetRoom:input_type -> booking.GetRoomRequest
	20, // 35: booking.RoomService.AddRelease:input_type -> booking.AddReleaseRequest
	25, // 36: booking.RoomService.UpdateRelease:input_type -> booking.UpdateReleaseRequest
	27, // 37: booking.RoomService.RemoveRelease:input_type -> booking.RemoveReleaseRequest
	17, // 38: booking.RoomService.ChangeRoomStatus:input_type -> booking.ChangeRoomStatusRequest
	22, // 39: booking.RoomService.PrepareReportData:input_type -> booking.PrepareReportDataRequest
	30, // 40: booking.RoomService.SetRoomArchived:input_type -> booking.SetRoomArchivedRequest
	31, // 41: booking.RoomService.SetRoomPublished:input_type -> booking.SetRoomPublishedRequest
	2,  // 42: booking.RoomService.CreateInitialRoom:output_type -> booking.CreateInitialRoomResponse
	4,  // 43: booking.RoomService.UpdateRoom:output_type -> booking.UpdateRoomResponse
	6,  // 44: booking.RoomService.AddRoomSlots:output_type -> booking.AddRoomSlotsResponse
	10, // 45: booking.RoomService.AddRoomEquipments:output_type -> booking.AddRoomEquipmentsResponse
	8,  // 46: booking.RoomService.UpdateRoomSlot:output_type -> booking.UpdateRoomSlotResponse
	12, // 47: booking.RoomService.UpdateRoomEquipment:output_type -> booking.UpdateRoomEquipmentResponse
	40, // 48: booking.RoomService.RemoveRoomSlot:output_type -> google.protobuf.Empty
	40, // 49: booking.RoomService.RemoveRoomEquipment:output_type -> google.protobuf.Empty
	14, // 50: booking.RoomService.GetRooms:output_type -> booking.GetRoomsResponse
	14, // 51: booking.RoomService.GetArchivedRooms:output_type -> booking.GetRoomsResponse
	16, // 52: booking.RoomService.GetRoom:output_type -> booking.GetRoomResponse
	21, // 53: booking.RoomService.AddRelease:output_type -> booking.AddReleaseResponse
	26, // 54: booking.RoomService.UpdateRelease:output_type -> booking.UpdateReleaseResponse
	40, // 55: booking.RoomService.RemoveRelease:output_type -> google.protobuf.Empty
	16, // 56: booking.RoomService.ChangeRoomStatus:output_type -> booking.GetRoomResponse
	23, // 57: booking.RoomService.PrepareReportData:output_type -> booking.PrepareReportDataResponse
	40, // 58: booking.RoomService.SetRoomArchived:output_type -> google.protobuf.Empty
	40, // 59: booking.RoomService.SetRoomPublished:output_type -> google.protobuf.Empty
	42, // [42:60] is the sub-list for method output_type
	24, // [24:42] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_room_service_proto_init() }
func file_room_service_proto_init() {
	if File_room_service_proto != nil {
		return
	}
	file_room_proto_init()
	file_address_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_room_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInitialRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInitialRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomSlotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomSlotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoomSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoomSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomEquipmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomEquipmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoomEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoomEquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeRoomStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRoomSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRoomEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReleaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareReportDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareReportDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReleaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveReleaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSorting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRoomArchivedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_service_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRoomPublishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_service_proto_goTypes,
		DependencyIndexes: file_room_service_proto_depIdxs,
		EnumInfos:         file_room_service_proto_enumTypes,
		MessageInfos:      file_room_service_proto_msgTypes,
	}.Build()
	File_room_service_proto = out.File
	file_room_service_proto_rawDesc = nil
	file_room_service_proto_goTypes = nil
	file_room_service_proto_depIdxs = nil
}
